[package]
name = "p_5"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.34.0"
vulkano-shaders = "0.34.0"
image = "0.24.0"
winit = "0.28.0"
rand = "0.8.5"
nalgebra-glm = "0.19.0"
nalgebra = "0.33.2"

