[package]
name = "main"
version = "0.1.1"
edition = "2021"

[dependencies]
winit = "0.28.0"
nalgebra-glm = "0.19.0"
renderer = { path = "../renderer" }
physics = { path = "../physics" }
noise = "0.9"
image = "0.25.5"