[package]
name = "renderer"
version = "0.1.1"
edition = "2021"

[dependencies]
draw_element = { path = "../draw_element"}
vulkano = "0.34.0"
vulkano-shaders = "0.34.0"
image = "0.25.5"
winit = "0.28.0"
rand = "0.8.5"
nalgebra-glm = "0.19.0"
nalgebra = "0.33.2"

